wandb: {}
project_name: kitti
#restore_ckpt: "./checkpoints/kitti4/50000.pth"
restore_ckpt: "/home/kemove/zxc/training_EH3D/MonSter-main_2D_double/MonSter-main_2D_scale_autodl/pretrained/120000.pth"
# restore_ckpt: "/data2/cjd/mono_fusion/checkpoints/sceneflow.pth"
logdir: '/media/kemove/zxc/ETH3D/checkpoints/kitti5/'
encoder: 'vitl'
batch_size: 1
train_datasets: ['kitti']
lr: 1e-4
wdecay: 1e-5
total_step: 100000  #50000
save_frequency: 2000
save_path: '/media/kemove/zxc/ETH3D/checkpoints/kitti5/'
val_frequency: 1   #之前是2000
image_size: [320, 736]
train_iters: 22     #22
valid_iters: 32
val_dataset: 'kitti'
corr_implementation: "reg"
corr_levels: 2
corr_radius: 4
n_downsample: 2
n_gru_layers: 3
hidden_dims: [128, 128, 128]
max_disp: 192
saturation_range: [0.7, 1.3]
do_flip: False
spatial_scale: [-0.2, 0.5]
noyjitter: True
num_gpu: 1
seed: 655
